Effect of plasticizers on melt processability and  properties of PHB  

M. RÂPĂa*, R.N. DARIE-NIŢĂb, E. GROSUa, E.E. TĂNASEc, A.R. TRIFOIa, T. PAPa, C. VASILEb 

aICPAO S.A., 8 Carpati St., 551022 Medias, Sibiu, Romania 

b„Petru Poni" Institute of Macromolecular Chemistry Iasi, 41A Grigore Ghica Voda Alley,700487 Iasi, Romania 

cUniversity of Agronomic Science and Veterinary Medicine Bucharest, Faculty of Biotehnologies, Blv. Marasti 59,  

011464 Bucharest, Romania 

Some results regarding plasticization of poly(3-hydroxybutyrate) (PHB) using triethyl citrate (TEC), acetyl o-tributyl citrate  (ATBC)  and  tributyl  citrate  (TBC)  are  presented.  The  blends  were  obtained  by  melt  mixing  procedure  on  a  Brabender  Plastograph at a temperature of 180oC, rotor speed of 60 rpm and mixing time of 6 minutes. The amounts of plasticizers  varied from 10 wt.% to 30 wt.% relative to PHB. The effect of plasticizer content on the melt viscosity, thermal properties  (DSC), spectral characteristics (ATR-FTIR), tensile properties and water permeability was investigated in order to improve  the processability and properties of PHB.  

(Received April 4, 2015; accepted October 28, 2015) 

1. Introduction 

However, PHB is still expensive, stiff and brittle [5].  Its  slow  crystallization  rates  lead  to  tacky  products  (e.g.  fibres, films, etc.) [6]. PHB is very sensitive to processing  conditions and exhibits a very narrow processing window  [7, 8]. The narrow processing window arises from its high  crystallinity  and  high  melting  temperature  of  the  crystalline domains. A high processing temperature (close  to  or  above  Tm)  is  required  where  unfortunately  the  thermal  degradation  becomes  significant.  Such  thermal  degradation  leads  to  random  scission  of  polymer  chains,  resulting  in  a  decrease  in  molecular  weight  and  further  reduction  of  the  melt  strength  [9].  In  principle,  this  problem  can  be  overcome  either  by  the  reduction  of  crystalline  melting  point  to  lower  the  processing  temperature or by some  means of reforming links in the  polymer being adopted (e.g., crosslinking) [9].  

Nowadays,  food  packages  market  is  in  ongoing  growth  in  order  to  accomplish  world  population’s  requirements.  Thus,  many  efforts  are  focused  on  developing  specific  packages  having  tailored  properties  such as mechanical, thermal, optical and barrier in order to  assure integral product quality [1].  

The  most  well-known packaging  materials  that  meet  these  criteria  are  those  based  on  petrochemical  sources.  However, these conventional plastics, manufactured from  fossil fuels are non-renewable and, furthermore, they have  a strong impact on environment.  

The  toughness  and  processability  of  PHB  can  be  improved  by  incorporation  of  the  hydroxyvalerate  (HV)  monomers in the bacterial fermentation process [6, 10] or  by introduction  of  additives,  like  plasticizers  [3]  and  nucleating agents [11] and formulations of composites and  blends based on PLA [12], PCL [13], cellulose/wood fiber  [4, 14, 15], poly(glycidyl methacrylate [9], etc.

Biopolymers produced from various natural resources  are  considered  attractive  alternatives  for  nonbiodegradable  petroleum-based  plastics  since  they  are  renewable,  environmentally  friendly  and  biodegradable  [2]. It is estimated that consumption of biopolymers will  grow  to  approximately  100  million  metric  tons/year  by  2020  in  Europe [3]. Poly(3-hydroxybutyrate)  (PHB)  is  a  polyester  and  one  of  the  most  widely  investigated  members  of  the  family  of  the  polyhydroxy  alkanoates  (PHAs). It is fully biodegradable, partially crystalline with  a  high  melting  temperature  (175  oC) and  high  degree  of  crystallinity  [2,  4].  PHB  offers  many  advantages  over  traditional  petrochemically  derived  plastics  for  food  packaging  applications,  being  completely  biodegradable  and nontoxic [3].  

Generally, plasticizers are added to both synthetic and  bio-based  polymeric  materials  to  impart  flexibility,  improve  toughness,  and  lower  the  glass  transition  temperature. Plasticizers constitute about one third of the  global additive market, with a worldwide consumption of  over 4.6 million metric tonnes in 2003 [6]. 

So  far,  as  plasticizers  for  PHB  have  been  reported  Lapol  108  (polyester  plasticizer) [12],  acetyl  tributyl  citrate  (ATBC)  [16],  poly(ethylene  glycol)  (PEG)  [17],  glycerol  [18],  limonene  [19],  etc.  Generally, all  investigated PHB-based blends were prepared by solvent  technique  and  contained  10  wt.%  of  plasticizer.  Few  papers described preparation of plasticized PHB by  melt  technique.  Thus,  Kurusu  et  al.  [20]  investigated  the  incorporation  of  three  industrial  plasticizers,  tri(ethylene  glycol)  bis(2-ethylhexanoate),  triethyl citrate and  tributyl  citrate in PHB via melt-mixing and studied the effect of  these additives through ageing and after annealing.  

In  this  paper,  the  plasticization  of  poly(3hydroxybutyrate)  using  triethyl  citrate  (TEC),  tributyl                    o-acetylcitrate (ATBC) and tributyl citrate (TBC) has been  studied  by  melt  mixing  procedure  on  a  Brabender  Plastograph  at  a  temperature  of  180oC,  rotor  speed  of                  60  rpm  and  mixing  time  of  6  minutes.  The  amounts  of  plasticizers  varied  from  10  wt.%  to  30  wt.%  relative  to  PHB.  The  effect  of  plasticizer  content  on  the  melt  viscosity,  thermal  properties  (DSC),  spectral  characteristics  (ATR-FTIR),  tensile  properties  and  water  permeability  was  investigated  in  order  to  improve  the  processability and properties of PHB. 

Melt blending of PHB/plasticizer blends  was carried  out in a Brabender Plastograph at temperature of 180oC,  rotor  speed  60  rpm  and  mixing  time  6  minutes.  Before  melting, PHB was dried at 50oC for 24 h. Three types of  blends  (polymer/plasticizer)  were  prepared  with  the  composition  of  polymer  to  plasticizer  as  follows:  PHB/ATBC - 90/10, 80/20 and 70/30 (wt/wt), PHB/TBC -  90/10  and  80/20  (wt/wt)  and  respectively  PHB/TEC  -  90/10, 80/20 and 70/30 (wt/wt). The plasticizer was mixed  with  PHB  before  being  loaded  into  the  Brabender  Plastograph. Once  the  melted  products  were  obtained,  were prepared sheets with dimensions (200 x 200 x 1) mm  and films with thickness of max. 100 µm by compressionmolding  using  a  hydraulic  press,  at  175oC  and  150  atm  pressure  for  3  min.  Specimens  for  characterization  were  cut from plates. 

# 2.3 Characterization 

2. Experimental 

2.3.1 Melt blending processing approach  

      2.1 Materials and Methods 

Processing  behavior  was  evaluated  by  analysis  of  processing  characteristics  following  the  torque  −  time  curves registered during blending in the Brabender mixer.  Thus,  torque  and  melt  viscosity  of  the  prepared  blends  were  evaluated  to  constant  values  of  6  min  at  60  rpm  based  on  rheological  data  reported  earlier  conforming  equations (1) and (2) [23]: 

In  the  current  study, PHB  in  the  powder  form  was  used; it was kindly supplied by BIOMER CO KRAILING  (Germany),  batch  no.  19T302/12/2106.  Three  types  of  food  grade  plasticizers  were  selected:  tributyl  citrate  (TBC), ≥ 97.0 %, batch no. BCBM 9410V were purchased  from  ALDRICH;  tributyl  o-acetylcitrate  (ATBC), batch  no.  0000000000000000  was  bought  from  PROVIRON  (Belgium);  and  triethyl  citrate  (TEC)  L12639,  batch  no.  10182084 was purchased from ALFA AESAS (Germany). Their  chemical  structure  and  properties  are  shown  in  Figure 1 and Table 1. 

M = C0Sa (1)

where:  M is  torque;  S is  the  rotor  speed  (rpm);  C0 is  a  constant depends on temperature; a is a constant. 

<table>
  <tr>
    &lt;td&gt; </td>
    &lt;td&gt; </td>
    &lt;td&gt; </td>
  </tr>
  <tr>
    &lt;td&gt;ATBC </td>
    &lt;td&gt;TBC </td>
    &lt;td&gt;TEC </td>
  </tr>
</table>

ζ = K                              (2)

where: ζ is shear stress;  is shear rate;   and n are the  power law parameters. 

Based on the equations (1) and (2) it can be deduced  that  the  torque  recorded  on  Brabender  is  an  indirect  indication of shear stress, while the rotor speed (rpm) is an  indirect indication of shear rate. Thus, the melt viscosity η is given as the ratio of shear stress to shear rate, and herein  can  be  obtained  from  the  ratio  of  torque  to  rotor  speed  (equation (3)) [24]:

Fig.1. Chemical structure of ecological plasticizers 

Table 1. Properties of the used plasticizers

<table>
  <tr>
    &lt;td&gt;Plasticizer </td>
    &lt;td&gt;Molecular  weight <br><br>(g mol-1) </td>
    &lt;td&gt;Density <br><br>(g L-1) </td>
    &lt;td&gt;Solubility  parameters </td>
  </tr>
  <tr>
    &lt;td&gt;Tributyl  citrate  (TBC) </td>
    &lt;td&gt;360.44 </td>
    &lt;td&gt;1.043 </td>
    &lt;td&gt;18.8 (J cm-3)1/2 [21] </td>
  </tr>
  <tr>
    &lt;td&gt;Tributyl oacetylcitrate  (ATBC) </td>
    &lt;td&gt;405.5 </td>
    &lt;td&gt;1.045 –  1.055 </td>
    &lt;td&gt;18.7 (J cm-3)1/2 [21] </td>
  </tr>
  <tr>
    &lt;td&gt;Triethyl  citrate  (TEC) </td>
    &lt;td&gt;276.28 </td>
    &lt;td&gt;1.137 </td>
    &lt;td&gt;22.7- 23.8  MPa1/2 [20,22]</td>
  </tr>
</table>

η = K(M/S)                        (3)

where K is a constant depends on temperature. 

2.3.2 Fourier transformation infrared (FT-IR)  

         spectroscopy studies 

In  order  to  evaluate  the  influence  of  plasticizers  on  PHB  blends,  the  films  were  analyzed  by  Fourier  Transform  Infrared  Spectroscopy  in  Attenuated  Total  Reflectance mode (FTIR - ATR) using a ZnSe crystal with  an  incidence  angle  of  45o.  All  spectra  represent  the  average of 20 scans recorded at 4 cm-1 resolution in a 2000  to 750 cm-1 range, using air as background. 

2.2 Preparation of the blends 

     2.3.3 Differential scanning calorimetry (DSC)  

              measurements 

Thermal  analysis  of  materials  was  carried  out  on  a  DSC  analyzer  (823e Mettler  Toledo).  Small  amounts  (about 5 mg) of dry samples were placed into aluminum  pans, sealed and first heated between 30 and 200oC at a  scanning  speed  of  10oC  /min.  The  samples  were  then  cooled to 30oC at a cooling rate of 10oC /min and heated  again to 200oC at 10oC /min. An empty aluminum pan was  used as reference. Melting temperature (Tm) and enthalpy  of  fusion  (ΔHf)  were  obtained  from  the  second  melting  endotherms.  Calibration  was  performed  using  an  indium  indium (m.p. = 156.6 oC; ΔHf = 28.45 J/g).  

The blend crystallinity degree was calculated using the  following equation [25]: 

Xc % = 100 x                                   (4) 

where: ΔHf is the melting enthalpy of the specimens (J/g);  is  the  enthalpy  value  for  a  theoretically  100%  crystalline PHB (146 J/g) [26].

2.3.4 Mechanical properties 

Mechanical  properties  were  measured  using  an  Instrom 3345 (USA) Testing. Tensile strength, elongation  at  break  and  Young’s  modulus  were  determined  on  a  dumbbell-shaped sheet with the following dimensions: 13  mm,  73  mm  and  1  mm  in  width,  gage  length  and  thickness, respectively, with the crosshead speed of 10 mm  min-1.  At  least  five  samples  were  tested  for  each  composition,  and  the  average  value  with  a  standard  deviation (SD) was reported.  

2.3.5 Water vapor permeability 

Water vapor  transmittance  rate  (WVTR)  of  the  samples was determined with PBI-Dansensor L 80-5000.  A dry room with a specified relative humidity is separated  by  a  wet  room  where  the  atmosphere  is  saturated  with  water  vapor  at  a  known  temperature  through  a  sheet  of  material  to  be  tested.  Changing  humidity  in  the  dry  chamber is achieved by  water vapor passing through the  tested material and is detected by a humidity sensor that is  able  to  provide  an  electrical  signal  that  is  measuring  relative  humidity  in  the  dry  room.  The  time  required  to  increase  humidity  to  a  certain  amount  is  measured  and  converted  into  a  transmission  rate  of  water  vapor.  The  permeability of the samples was performed at 23°C. 

3.1 Processing characteristics of PHB/plasticizer  

       blends  

In Fig. 2 are shown the plastograms of plastified PHB  melted at a temperature of 180oC, rotor speed of 60 rpm  and mixing time of 6 minutes. 

The  addition  of  plasticizer  led  to  the  lower  level  of  torque  and  lower  melt  viscosity,  as  it  can  be  seen  from  Figures 2 and 3. 

Fig.2. Brabender torque-time profiles of plastified PHB

Fig.3. Melt viscosity index of plastified PHB at different  

loadings of plasticizer 

From Fig. 2 is observed that at 6 minutes the torque  decreased  as  the  plasticizer  content  increased.  With  increasing  of  plasticizer  content,  the  viscosity  decreased  for  all  types  of  plasticizers  (Figure  3).  This  decrease  indicates that the chains of PHB are easily deformed and  their frictional resistance is not optimum.  

All  plasticizers  used  were  found  very  suitable  to  plasticize  the  PHB,  among  which  TBC  is  the  most  effective plasticizer for significantly improvement of PHB  processability.  Melt  viscosity  index  of  PHB  blends  decreased  as  follows:  TEC-10  ˃  ATBC-10  ˃  TBC-10;  TEC-20 ˃ ATBC-20 ˃ TBC-20; TEC-30 ˃ ATBC-30.  

3.2 FTIR-ATR Analysis 

The effect of three plasticizers on FTIR spectrum on  PHB is presented in Figure 4. Neat PHB (as powder) was  used as reference. 

From literature, the main bands of PHB are assigned  to C–O–C stretching at 1188 cm-1 [27], C-O-C stretching  at 1227 cm-1, wag CH3 at 1380 cm-1 [28], assym. CH3 at 

1456  cm-1 and  crystalline  C=O  at  1724  cm-1 [28,  29].  Characteristic  bands  associated  to  plastified  PHB  are  shifted  to  lower  wavenumber,  as  the  plasticizer  content  increases. Therefore, neat PHB shows a band at 1182 cm-1 

The crystalline band at 1724 cm-1 is shifted to 1720  cm-1 for  PHB/ATBC-10,  PHB/ATBC-30,  PHB/TEC  and  PHB/TBC-20 samples and to 1718 cm-1 for PHB/ATBC20  and  PHB/TBC-10  samples.  This  indicated  that  plasticizer  could  decrease  the  wavenumber  of  the  characteristic peaks. The same decrease of wavenumber to  lower  frequency  was  observed  by  Wang  et  al.  for  characteristic bands of PLA/carbon black composites with  increasing plasticizers content [30]. 

that  is  shifted  to  1180  cm-1 and  to  1178  cm-1 for  PHB/ATBC-10 and respectively PHB/ATBC-20.

3.3 DSC Spectra  

The  thermal  properties  as  Tc,  Tm,  Hf and Xc  of  PHB/plasticizer blends, obtained from the second heating,  are summarized in Table 2.  

800 1000 1200 1400 1600 1800 2000 Transmittance (%) Wavenumbers (1/cm) Neat PHB PHB/ATBC10 PHB/ATBC20 PHB/ATBC30 (a) 800 1000 1200 1400 1600 1800 2000 Transmittance (%) Wavenumbers (1/cm) Neat PHB PHB/TEC10 PHB/TEC20 (b) PHB/TEC30 800 1000 1200 1400 1600 1800 2000 Transmittance (%) Wavenumbers (1/cm) Neat PHB PHB/TBC10 (c) PHB/TBC20

Table 2. DSC results of PHB/plasticizer blends 

<table>
  <tr>
    &lt;td&gt;Sample code </td>
    &lt;td&gt;Tc (oC) </td>
    &lt;td&gt;Tm (oC) </td>
    &lt;td&gt;Hf (J/g) </td>
    &lt;td&gt;Xc (%) </td>
  </tr>
  <tr>
    &lt;td&gt;PHB pure </td>
    &lt;td&gt;87.1 </td>
    &lt;td&gt;173.5 </td>
    &lt;td&gt;89.0 </td>
    &lt;td&gt;60.9 </td>
  </tr>
  <tr>
    &lt;td&gt;PHB/ATBC10 </td>
    &lt;td&gt;81.1 </td>
    &lt;td&gt;166.9 </td>
    &lt;td&gt;82.8 </td>
    &lt;td&gt;56.7 </td>
  </tr>
  <tr>
    &lt;td&gt;PHB/ATBC20 </td>
    &lt;td&gt;80.7 </td>
    &lt;td&gt;167.3 </td>
    &lt;td&gt;78.8 </td>
    &lt;td&gt;53.9 </td>
  </tr>
  <tr>
    &lt;td&gt;PHB/ATBC30 </td>
    &lt;td&gt;80.8 </td>
    &lt;td&gt;158.2 </td>
    &lt;td&gt;67.2 </td>
    &lt;td&gt;46.0 </td>
  </tr>
  <tr>
    &lt;td&gt;PHB/TEC10 </td>
    &lt;td&gt;79.7 </td>
    &lt;td&gt;168.1 </td>
    &lt;td&gt;80.0 </td>
    &lt;td&gt;54.8 </td>
  </tr>
  <tr>
    &lt;td&gt;PHB/TEC20 </td>
    &lt;td&gt;70.2 </td>
    &lt;td&gt;168.4 </td>
    &lt;td&gt;61.6 </td>
    &lt;td&gt;42.2 </td>
  </tr>
  <tr>
    &lt;td&gt;PHB/TEC30 </td>
    &lt;td&gt;65.2 </td>
    &lt;td&gt;162.8 </td>
    &lt;td&gt;59.7 </td>
    &lt;td&gt;40.9 </td>
  </tr>
  <tr>
    &lt;td&gt;PHB/TBC10 </td>
    &lt;td&gt;75.4 </td>
    &lt;td&gt;171.9 </td>
    &lt;td&gt;85.7 </td>
    &lt;td&gt;58.6 </td>
  </tr>
  <tr>
    &lt;td&gt;PHB/TBC20 </td>
    &lt;td&gt;69.8 </td>
    &lt;td&gt;168.1 </td>
    &lt;td&gt;75.4 </td>
    &lt;td&gt;51.6 </td>
  </tr>
</table>

The data from Table 2 revealed that the enthalpy of  PHB fusion, ∆Hf, decreased from 89.0 J/g to 67.2 J/g for  PHB with 30% ATBC, to 59.7 J/g for PHB with 30% TEC  and respectively to 75.4 J/g for PHB with 20% TBC. In  addition, the Tc value of blends showed lower values than  pure PHB. 

The effect of plasticizer content on Tm and Xc of PHB/ 

plasticizer blends is also shown in Figure 5. The pure PHB  powder  showed  one  endotherm  peak  at  173.5oC.  A  depression  of  Tm was  observed  in  all  PHB/plasticizer  blends in comparison with pure PHB (Fig. 5 (a)). Erceg et  al.  [16] investigated  the  effect  of  acetyl  tributyl  citrate  (ATBC)  on  the  thermal  stability  of  PHB  by  DSC  and  showed  that  ATBC  leads  to  significant  decrease  in  Tm.  From  Fig.  5  (a)  is  observed  that  once  the  plasticizer  content  increased,  the  Tm decreased.  As  a  result,  the  processing  temperature  window  is  increased.  This  is  in  good  agreement  with  lower  viscosity  recorded  for  PHB  loaded  with  plasticizers,  making  them  the  easier  for  processing. 

From the melting temperature of PHB blends, it can  be concluded that the efficiency of plasticizers was higher  in the order: TBC-10 ˃ TEC-10 ˃ ATBC-10; TEC-20 ˃  TBC-20 ˃ ATBC-20; TEC-30 ˃ ATBC-30.  

 From  Fig.  5  (b)  is  observed  that  Xc decreased  with  loading  of  plasticizers.  With  increasing  of  plasticizer  contents, the PHB  microcrystals or ordered chains could  be  more  easily  moved  to  unpack  into  a  little  dense  or  perfect crystalline structure [31]. The Xc of pure PHB was  60.9%. The lowest value of Xc is recorded by PHB/TEC30  blend (40.9%).  

Fig.  4.  Effect  of  plasticizer  type  and  concentration  on  FTIR  spectrum  of  PHB/plasticizer  films(a)  Plasticized  with ATBC;  (b)  Plasticized  with  TEC;  (c)  Plasticized  

with TBC

It is noted that the trend of decrease of PHB/plasticizer  blends  crystallinity  (Xc)  degree  is  obvious  in  the  order:  TBC-10  ˃  ATBC-10  ˃  TEC-10; ATBC-20  ˃  TBC-20  ˃  TEC-20; ATBC-30 ˃ TEC-30.  

Fig. 5. Thermal properties  of PHB/plasticizer blends 

(a) Melting temperature; (b) Degree of crystallinity

3.4 Tensile properties 

The effect of type and concentration of plasticizer on  the  mechanical  properties  of  PHB/plasticizer  blends  (tensile  strength,  elongation  at  break,  and  Young's  modulus) are shown in Figure 6.  

From Figure 6 is evidenced that loading of plasticizer  leads to improve of elongation at break with the detriment  of tensile strength. The addition of  ATBC decreased the  tensile  strength  of  PHB  blends  at  about  25%  for  blend  containing  ATBC in  content  of  20% and  respectively  at  59%  for  30%  ATBC  compared  with  PHB/ATBC-10  sample.  Also,  TEC  led  to  a  decrease  of  tensile  strength  with 27% for blends containing 20% TEC and with 51%  for 30% TEC since a lower decrease at 16 % was recorded  for  PHB/TBC-20  (Figure  6  (a)).  It  is  showed  a  significantly  increase  of  elongation  at  break  for  PHB/ATBC-30,  PHB/TBC-20  blends  (95%  higher  than  PHB/TBC-10)  and  for  PHB/ATBC-20  (62%  higher  than  PHB/ATBC-10) (Figure 6 (b)). PHB/TEC blends display a  maximum elongation at break of 31% for loading of 30%  TEC. These results were in agreement with the outcome of  other  researchers  that  found  that  increase  in  the  PEG  content  reduced  the  tensile  strength  and  increased  the  elongation at break of pure PHB [17].

10 15 20 25 30 8 10 12 14 16 18 20 22 24 26 28 30 32 Tensile strength (MPa) Plasticizer content (%)  PHB/ATBC  PHB/TEC  PHB/TBC (a) 5 10 15 20 25 30 35 0 1 2 3 4 5 6 7 8 9 Elongation a break (%) Plasticizer content (%)  PHB/ATBC  PHB/TEC  PHB/TBC (b) 10 15 20 25 30 600 800 1000 1200 1400 1600 1800 2000 2200 Young's Modulus (MPa) Plasticizer content (%)  PHB/ATBC  PHB/TEC  PHB/TBC (c)

Fig. 6. Effect of plasticizer type and concentration on tensile  properties  of  PHB/plasticizer  blends  (a)  Tensile  strength;               (b) Elongation at Break;(c) Young’s Modulus. Error bars  

represent standard error, n = 5 

It is recognized that plasticization reduces the relative  number of polymer–polymer contacts thereby decreasing  the  rigidity  of  the  three-dimensional  structure  thereby  allowing  deformation  without  rupture  [6].  Young’s  modulus follows the same decreased trend than evidences  of tensile strength variation (Fig. 6 (c)). 

It  should  be  noted  that  the  solubility  parameters  of  PHB  that  has  been  reported  to  range  between  18.5  and  20.1  MPa1/2  [32]  [37.85  -  41.12  (J/cm3)1/2] are  closed  to 

those of TEC [48.69 (J/cm3)1/2]. This indicated that PHB  should  interact  well  with  TEC.  The  highest  solubility  parameter of TEC may result in the higher strain at break compared  to  the  blends  containing  ATBC  and  TBC.  However,  the  rank  of  these  solubility  parameters  cannot  explain  the  lowest  elongation  at  break  of  the  PHB  containing TEC. This can be due to the lowest molecular  weight  of  TEC  (276.28  g/mol)  causing  the  lowest  intermolecular  attraction  of  PHB  leading  to  the  lowest  elongation. Tensile properties reveal that the most efficient  plasticizer  is  TBC  followed  by  ATBC.  Depending  on  desired properties of the final products it could be selected  the optimal concentration of plasticizer. 

The  addition  of  plasticizer  led  to  the  lower  level  of  torque. The melt viscosity index of PHB blends decreased  as  follows:  TEC-10˃ATBC-10˃TBC-10;  TEC-20˃  ATBC-20˃TBC-20; TEC-30 ˃ATBC-30. PHB/plasticizer  blends exhibited a wider melt-processing window. FT-IR  spectroscopy revealed that the increase of plasticizer leads  to  reduction  of  the  wavenumber  for  the  characteristic  bands  of  PHB  (1182  cm-1,  1724  cm-1).  Incorporation  of  plasticizers  into  PHB  decreased  tensile  strength  and  Young's  modulus,  but  increased  the  elongation  at  break.  WVTR was found to be dependent on the type and content  of plasticizer. TBC and ATBC were the most compatible  and  efficient  plasticizers  on  improving  the  thermal,  mechanical and barrier properties of PHB. The optimum  concentration  could  be  up  to  20%  depending  on  the  desired properties of final products.  

The findings of this study will also provide foundation  for further developments of bioactive food packaging from  PHB, ecological plasticizers and bioactive compounds. 

3.5 Water vapor permeability

Water vapor transmittance rate (WVTR) of the films  prepared by the plasticization of PHB  with ATBC, TEC  and respectively TBC is presented in Figure 7. 

The  research  leading  to  these  results  has  received  funding from the Romanian - EEA Research Programme  operated  by  MEN  under  the  EEA  Financial  Mechanism  2009-2014  and  Project  ACTIBIOSAFE,  Contract  No  1SEE/30.06.2014. 

10 15 20 25 30 5 10 15 20 25 30 35 40 45 50 55 60 65 2WVTR (g/m  day) Plasticizer content (wt. %)  PHB/ATBC  PHB/TEC  PHB/TBC

S.E. Barbosa, Food Hydrocolloids 43, 18 (2015).  

         Hydrocolloids 39, 77 (2014). 

        Innovative Research in Science, Engineering and  

        Technology 3 (2), 9494 (2014). 

Fig.7. WVTR of PHB/plasticizer films

        Journal of Cleaner Production 41, 312 (2013). 

Data  showed  in  Fig.  7  emphasize  that  WVTR  is  dependent on the type and level of plasticizer. It was found  to  be  in  the  range  of  5.97  to  6.90  g/m2  day.  A  higher  WVTR is recorded by PHB/TEC blend.  

        C.A. Ribeiro, Y. Messaddeq, S.J.L. Ribeiro,  

         Carbohydrate Polymers 83, 1279 (2011). 

It is known that the degree of crystallinity influences  inversly  proportional  the  permeability  of  samples.  A  higher degree of crystallinity is  usually related  with  low  permeability  of  the  films  (as  crystals  restricting  chain  mobility) [27]. From Figure 6, is shown that PHB/TBC10  reached  the  higher  value  for  Xc,  and  PHB/TEC  blends  recorded the lowest Xc this being in accordance with the  permeability variation.

        H. Khalilb, D. Bressler, Journal of Materials  

        Chemistry A 1, 13379 (2013). 

50, 6139 (2009). 

        S.K. Bhatia, A.K. Mohanty, Progress in Polymer  

         Science (2013). 

        Part A: Polymer Chemistry 40, 351–358 (2002). 

4. Conclusions 

        Biodeterioration &amp; Biodegradation 87, 1 (2014). 

The results of this study evidenced the effect of three  types of plasticizers, named acetyl o-tributylcitrate, triethyl  citrate  and  tributhyl  citrate  on  melt  processability  and  properties of PHB.  

        G. Scarinzi, M. Malinconico, International Journal of  

        Biological Macromolecules 71,163 (2014). 

        W. Orts, E. Chiellini, Polymer Degradation and  

       Stability 97, 1822-1828 (2012). 

## [13] D. Lovera, L. Márquez, V. Balsamo, A. Taddei,  

##         C. Castelli, A.J. Müller, Macromolecular Chemistry 

## and Physics 208 (9), 924 (2007).

        C. Stanescu, Materiale Plastice 47(4), 503 (2010). 

27(3), ISSN 1454-2331, 3-10 (2010). 

        and Stability 90, 313 (2005). 

Polymer Degradation and Stability

 91(9), 1954 (2006). 

        and Stability 77 (1), 35 (2002). 

        European Polymer Journal 50, 255 (2014). 

        N.R. Demarquette, C. Gauthier, J.M. Chenal, Ind. 

        Crops Prod. (2015). 

        S.P. Mccarthy, Journal of Applied Polymer Science 

66, 1507 (1997).  

23, 455 (2004). 

        Science 7, 178 (1967). 

8 (3), 167 (1999). 

        Thermochimica Acta 423, 127 (2004). 

         Polymer Degradation and Stability 95, 2318 (2010). 

        Y.M. Corre, Y. Grohens, Polymer Testing  

32, 842 (2013). 

        Z.M. Zhang, Polymer 43, 6893 (2002). 

744–747, 529 (2005).  

        Degradation and Stability 93, 1044 (2008). 

        Applied Polymer Science 102, 3782 (2006). 

        N.R. Demarquette, A. Bogner, J.Y. Cavaille, Polym.  

        Int. 61, 434 (2012).